# This workflow runs whenever a PR is opened or updated, or a commit is pushed to main. It runs
# several checks:
# - fmt: checks that the code is formatted according to rustfmt
# - clippy: checks that the code does not contain any clippy warnings
# - doc: checks that the code can be documented without errors
# - deny: checks dependency licensing and advisories with cargo-deny
# - msrv: check that the msrv specified in the crate is correct
permissions:
  contents: read
# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches: [main]
  pull_request:
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: check
jobs:
  fmt:
    runs-on: ubuntu-latest
    name: nightly / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy (${{ matrix.feature }})
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: stable
            feature: default
            clippy_flags: -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: stable
            feature: async
            clippy_flags: --features async -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: stable
            feature: defmt-03
            clippy_flags: --features defmt-03 -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: stable
            feature: all
            clippy_flags: --all-features -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: beta
            feature: default
            clippy_flags: -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: beta
            feature: async
            clippy_flags: --features async -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: beta
            feature: defmt-03
            clippy_flags: --features defmt-03 -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
          - toolchain: beta
            feature: all
            clippy_flags: --all-features -- -F clippy::suspicious -F clippy::correctness -F clippy::perf -F clippy::style
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo clippy (${{ matrix.feature }})
        uses: giraffate/clippy-action@v1
        with:
          reporter: "github-pr-check"
          clippy_flags: ${{ matrix.clippy_flags }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Enable once we have a released crate
  # UPDATE: Crate is released but because of mutually exclusive features, this will never succeed :c
  # semver:
  #   runs-on: ubuntu-latest
  #   name: semver
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: Install stable
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         components: rustfmt
  #     - name: cargo-semver-checks
  #       uses: obi1kenobi/cargo-semver-checks-action@v2

  doc:
    # run docs generation on nightly rather than stable. This enables features like
    # https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html which allows an
    # API be documented as only available in some specific platforms.
    # UPDATE: nightly seems broken right now, reverting to stable
    runs-on: ubuntu-latest
    name: stable / doc (${{ matrix.feature }})
    strategy:
      matrix:
        include:
          - toolchain: stable
            feature: default
            cargo_doc_args: ""
          - toolchain: stable
            feature: async
            cargo_doc_args: "--features async"
          - toolchain: stable
            feature: defmt-03
            cargo_doc_args: "--features defmt-03"
          - toolchain: stable
            feature: all
            cargo_doc_args: "--all-features"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo doc (${{ matrix.feature }})
        run: cargo doc --no-deps ${{ matrix.cargo_doc_args }}
        env:
          RUSTDOCFLAGS: --cfg docsrs

  deny:
    # cargo-deny checks licenses, advisories, sources, and bans for
    # our dependencies.
    runs-on: ubuntu-latest
    name: ubuntu / stable / deny
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo install cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          manifest-path: ./Cargo.toml
          command: check
          arguments: --all-features

  msrv:
    # check that we can build using the minimal rust version that is specified by this crate
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        include:
          - msrv: "1.85"
            toolchain: stable
            feature: default
            cargo_check_args: ""
          - msrv: "1.85"
            toolchain: stable
            feature: async
            cargo_check_args: "--features async"
          - msrv: "1.85"
            toolchain: stable
            feature: defmt-03
            cargo_check_args: "--features defmt-03"
          - msrv: "1.85"
            toolchain: stable
            feature: all
            cargo_check_args: "--all-features"
    name: ubuntu / ${{ matrix.msrv }} / ${{ matrix.feature }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - name: cargo +${{ matrix.toolchain }} check (${{ matrix.feature }})
        run: cargo check ${{ matrix.cargo_check_args }}
