# This workflow checks whether the library is able to run without the std library (e.g., embedded).
# This entire file should be removed if this crate does not support no-std. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: no-std
jobs:
  nostd:
    runs-on: ubuntu-latest
    name: ${{ matrix.target }} / ${{ matrix.feature }}
    strategy:
      matrix:
        include:
          - target: thumbv8m.main-none-eabihf
            feature: default
            cargo_check_args: ""
          - target: thumbv8m.main-none-eabihf
            feature: async
            cargo_check_args: "--features async"
          - target: thumbv8m.main-none-eabihf
            feature: defmt-03
            cargo_check_args: "--features defmt-03"
          - target: thumbv8m.main-none-eabihf
            feature: all
            cargo_check_args: "--all-features"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: rustup target add ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}
      - name: cargo check (${{ matrix.feature }})
        run: cargo check --target ${{ matrix.target }} ${{ matrix.cargo_check_args }}
